export enum StatusEntrega {
    AGUARDANDO_ENVIO = 'AGUARDANDO_ENVIO',
    EM_TRANSPORTE = 'EM_TRANSPORTE',
    ENTREGUE = 'ENTREGUE',
    FALHA_NA_ENTREGA = 'FALHA_NA_ENTREGA',
    CANCELADO = 'CANCELADO',
}